name: Build, Test and Release

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

permissions:
  id-token: write
  contents: write

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        example_dir:
          - examples/v9-managed-react
          - examples/v9-simple-react
          - examples/v9-managed-vite5-react
          - examples/v10-managed-react
          - examples/v10-simple-react
          - examples/v10-managed-vite5-react
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn e2e ${{ matrix.example_dir }}
        env:
          CI: true
      - run: yarn deploy:ci
        if: ${{ github.ref_name == 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
